// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu04eYCEJpY7bOAumemCF8vHq99zPhSh0',
    appId: '1:878764507418:web:62e1007c5203ecf0802ca3',
    messagingSenderId: '878764507418',
    projectId: 'testproject-fb549',
    authDomain: 'testproject-fb549.firebaseapp.com',
    storageBucket: 'testproject-fb549.appspot.com',
    measurementId: 'G-M72H3WLLL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfg6nyd6Kb-tMS5CFvOCJArSlsuMxj_2s',
    appId: '1:878764507418:android:de77d2dabeea9fb8802ca3',
    messagingSenderId: '878764507418',
    projectId: 'testproject-fb549',
    storageBucket: 'testproject-fb549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0oVPHJKw1DWtQb2Zfq4g-vuM7niVV45Q',
    appId: '1:878764507418:ios:b786931584777b7c802ca3',
    messagingSenderId: '878764507418',
    projectId: 'testproject-fb549',
    storageBucket: 'testproject-fb549.appspot.com',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0oVPHJKw1DWtQb2Zfq4g-vuM7niVV45Q',
    appId: '1:878764507418:ios:931eb05e7cbcffed802ca3',
    messagingSenderId: '878764507418',
    projectId: 'testproject-fb549',
    storageBucket: 'testproject-fb549.appspot.com',
    iosBundleId: 'com.example.testproject.RunnerTests',
  );
}
